name: Build and Deploy to prod service app

on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string
      is-release:
        required: true
        type: string
      tag-name:
        required: true
        type: string

jobs:
  get-version:
    name: Get version from package-lock.json
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: 'elrayle/reusable'
          path: 'reusable'

      - name: Get version from package-lock.json
        id: get_version
        shell: bash
        run: |
          version=$(./reusable/scripts/app-workflows/get-version.sh ${{ inputs.deploy-env }} ${{ inputs.is-release }} ${{ inputs.tag-name }} ${{ github.sha }})
          echo "version=$version"
          echo "VERSION=$version" >> $GITHUB_ENV
