name: Build and Deploy to prod service app

on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string
      is-release:
        required: true
        type: string
      tag-name:
        required: true
        type: string

jobs:
  get-version:
    name: Get version from package-lock.json
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Download package-lock.json
        uses: actions/download-artifact@v4
        with:
          name: package-lock.json
          path: .

      - uses: actions/checkout@v4.1.1
        with:
          repository: 'elrayle/reusable'
          ref: 'v1.0.0-rc4'
          path: 'reusable'

      - name: Get version from package-lock.json
        id: get_version
        shell: bash
        run: |
          version_log=$(./reusable/scripts/app-workflows/get-version.sh \
            ${{ inputs.deploy-env }} \
            ${{ inputs.is-release }} \
            ${{ inputs.tag-name }} \
            ${{ github.sha }})
          echo "version_log=$version_log"
          echo "VERSION=$(version_log | tail -n)" >> $GITHUB_ENV
